# Generated by Django 4.2.28 on 2026-04-23 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='نام کسب\u200cوکار/شخص')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('shop', 'مغازه'), ('company', 'شرکت'), ('person', 'شخص'), ('service', 'خدمات')], default='shop', max_length=20)),
                ('activity', models.CharField(max_length=180, verbose_name='حوزه فعالیت')),
                ('city_name', models.CharField(blank=True, default='', max_length=120, verbose_name='نام شهر (اگر City نداری)')),
                ('short_description', models.TextField(blank=True, default='', max_length=500)),
                ('about_text', models.TextField(blank=True, default='', verbose_name='متن معرفی/درباره ما')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='تلفن')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=30, verbose_name='واتساپ (شماره)')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کسب\u200cوکار/صفحه معرفی',
                'verbose_name_plural': 'کسب\u200cوکارها',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
            },
        ),
        migrations.CreateModel(
            name='BusinessSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=160, verbose_name='SEO Title')),
                ('description', models.CharField(blank=True, default='', max_length=320, verbose_name='SEO Description')),
                ('keywords', models.CharField(blank=True, default='', max_length=250, verbose_name='SEO Keywords')),
                ('og_image', models.URLField(blank=True, default='', verbose_name='OG Image URL')),
                ('robots_index', models.BooleanField(default=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='businesses.business')),
            ],
            options={
                'verbose_name': 'تنظیمات سئو',
                'verbose_name_plural': 'تنظیمات سئو',
            },
        ),
        migrations.CreateModel(
            name='BusinessAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, default='', max_length=120, verbose_name='استان')),
                ('address_line1', models.CharField(blank=True, default='', max_length=220, verbose_name='آدرس ۱ (خیابان/پلاک)')),
                ('address_line2', models.CharField(blank=True, default='', max_length=220, verbose_name='آدرس ۲ (پلاک/طبقه/…)')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='کدپستی')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('google_map_url', models.URLField(blank=True, default='', verbose_name='لینک گوگل مپ')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='businesses.business')),
            ],
            options={
                'verbose_name': 'آدرس کسب\u200cوکار',
                'verbose_name_plural': 'آدرس\u200cها',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='businesses.city'),
        ),
    ]
