# Generated by Django 4.2.30 on 2026-06-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'کسب\u200cوکار', 'verbose_name_plural': 'کسب\u200cوکارها'},
        ),
        migrations.AlterModelOptions(
            name='businessaddress',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس\u200cها'},
        ),
        migrations.AddField(
            model_name='business',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='businesses/logos/', verbose_name='لوگو / تصویر'),
        ),
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, default='', verbose_name='وب\u200cسایت'),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('shop', 'مغازه'), ('company', 'شرکت'), ('person', 'شخص / فریلنسر'), ('service', 'خدمات')], default='shop', max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='واتساپ'),
        ),
        migrations.AlterField(
            model_name='businessaddress',
            name='address_line1',
            field=models.CharField(blank=True, default='', max_length=220, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='businessaddress',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=220, verbose_name='آدرس ۲'),
        ),
        migrations.AlterField(
            model_name='businessseo',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Keywords'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_active', '-created_at'], name='businesses__is_acti_d0e678_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['activity'], name='businesses__activit_36255d_idx'),
        ),
    ]
