# Generated by Django 4.2.28 on 2026-06-17 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_business_options_alter_businessaddress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='businesses/qrcodes/', verbose_name='QR Code'),
        ),
        migrations.CreateModel(
            name='BusinessSocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(blank=True, default='', max_length=100, verbose_name='اینستاگرام (یوزرنیم)')),
                ('telegram', models.CharField(blank=True, default='', max_length=100, verbose_name='تلگرام (یوزرنیم یا لینک)')),
                ('linkedin', models.URLField(blank=True, default='', verbose_name='لینکدین (URL)')),
                ('twitter', models.CharField(blank=True, default='', max_length=100, verbose_name='توییتر/X (یوزرنیم)')),
                ('youtube', models.URLField(blank=True, default='', verbose_name='یوتیوب (URL)')),
                ('aparat', models.CharField(blank=True, default='', max_length=100, verbose_name='آپارات (یوزرنیم)')),
                ('rubika', models.URLField(blank=True, default='', verbose_name='روبیکا (URL)')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='businesses.business')),
            ],
            options={
                'verbose_name': 'شبکه\u200cهای اجتماعی',
                'verbose_name_plural': 'شبکه\u200cهای اجتماعی',
            },
        ),
    ]
