# Generated by Django 4.2.28 on 2026-06-17 20:17

import app.businesses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_qr_code_businesssociallinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssociallinks',
            name='bale',
            field=models.CharField(blank=True, default='', help_text='یوزرنیم یا لینک کامل t.me مثل @username', max_length=120, verbose_name='بله (یوزرنیم یا لینک)'),
        ),
        migrations.AddField(
            model_name='businesssociallinks',
            name='eitaa',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='ایتا (یوزرنیم یا لینک)'),
        ),
        migrations.AddField(
            model_name='businesssociallinks',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='فیسبوک (یوزرنیم یا URL)'),
        ),
        migrations.AddField(
            model_name='businesssociallinks',
            name='gap',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='گپ (یوزرنیم)'),
        ),
        migrations.AddField(
            model_name='businesssociallinks',
            name='pinterest',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='پینترست (یوزرنیم)'),
        ),
        migrations.AddField(
            model_name='businesssociallinks',
            name='snapchat',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='اسنپ\u200cچت (یوزرنیم)'),
        ),
        migrations.AddField(
            model_name='businesssociallinks',
            name='soroush',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='سروش (یوزرنیم)'),
        ),
        migrations.AddField(
            model_name='businesssociallinks',
            name='tiktok',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='تیک\u200cتاک (یوزرنیم)'),
        ),
        migrations.AlterField(
            model_name='businesssociallinks',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='تلگرام (یوزرنیم یا لینک)'),
        ),
        migrations.CreateModel(
            name='BusinessTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False, verbose_name='کارت ویزیت لوکس (Premium)')),
                ('theme', models.CharField(choices=[('default', 'پیش\u200cفرض سایت'), ('gold_black', 'طلایی / مشکی'), ('silver_dark', 'نقره\u200cای / تیره'), ('rose_gold', 'رز گلد'), ('midnight_blue', 'آبی تیره شب')], default='default', max_length=30, verbose_name='تم رنگی')),
                ('font', models.CharField(choices=[('vazirmatn', 'وزیرمتن'), ('yekan', 'یکان'), ('sahel', 'ساحل'), ('dana', 'دانا')], default='vazirmatn', max_length=30, verbose_name='فونت')),
                ('primary_color', models.CharField(blank=True, default='', help_text='مثال: #C9A84C', max_length=20, verbose_name='رنگ اصلی (hex)')),
                ('secondary_color', models.CharField(blank=True, default='', max_length=20, verbose_name='رنگ ثانویه (hex)')),
                ('background_color', models.CharField(blank=True, default='', max_length=20, verbose_name='رنگ پس\u200cزمینه (hex)')),
                ('text_color', models.CharField(blank=True, default='', max_length=20, verbose_name='رنگ متن (hex)')),
                ('header_bg_image', models.ImageField(blank=True, null=True, upload_to='businesses/themes/', verbose_name='تصویر پس\u200cزمینه هدر')),
                ('tagline', models.CharField(blank=True, default='', max_length=120, verbose_name='شعار / تگ\u200cلاین')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='businesses.business')),
            ],
            options={
                'verbose_name': 'تم کارت ویزیت',
                'verbose_name_plural': 'تم\u200cهای کارت ویزیت',
            },
        ),
        migrations.CreateModel(
            name='BusinessEndorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_name', models.CharField(help_text='مثال: رئیس اتاق اصناف تهران', max_length=120, verbose_name='نام صادرکننده')),
                ('issuer_title', models.CharField(blank=True, default='', max_length=120, verbose_name='سمت صادرکننده')),
                ('issuer_photo', models.ImageField(blank=True, null=True, upload_to='businesses/endorsements/', verbose_name='عکس صادرکننده')),
                ('endorsement_text', models.TextField(help_text='متن دقیق تاییدیه که روی کارت نمایش داده میشه', verbose_name='متن تاییدیه')),
                ('badge_label', models.CharField(blank=True, default='', help_text='مثال: «تایید شده توسط اتاق اصناف» — اگه خالی باشه نام صادرکننده نشون داده میشه', max_length=60, verbose_name='برچسب badge')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='تاریخ صدور')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='businesses.business')),
            ],
            options={
                'verbose_name': 'تاییدیه',
                'verbose_name_plural': 'تاییدیه\u200cها',
                'ordering': ['order', '-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان فایل')),
                ('doc_type', models.CharField(choices=[('license', 'مجوز / پروانه فعالیت'), ('catalog', 'کاتالوگ / بروشور'), ('resume', 'رزومه'), ('portfolio', 'نمونه کار'), ('price_list', 'لیست قیمت'), ('cert', 'گواهینامه / افتخارنامه'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع سند')),
                ('file', models.FileField(upload_to=app.businesses.models.business_document_upload_path, verbose_name='فایل')),
                ('description', models.CharField(blank=True, default='', max_length=220, verbose_name='توضیح کوتاه')),
                ('is_public', models.BooleanField(default=True, help_text='اگه غیرفعال باشه فقط در پنل ادمین قابل مشاهده\u200cست', verbose_name='نمایش عمومی')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='businesses.business')),
            ],
            options={
                'verbose_name': 'فایل / سند',
                'verbose_name_plural': 'فایل\u200cها / اسناد',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
